/* 
   SDS, a bridge single-suit double-dummy quick-trick solver.

   Copyright (C) 2015-16 by Soren Hein.

   See LICENSE and README.
*/

#ifndef SDS_COMPARE_H
#define SDS_COMPARE_H

enum CmpType
{
  SDS_SAME = 0, 
  SDS_NEW_BETTER = 1, 
  SDS_OLD_BETTER = 2, 
  SDS_DIFFERENT = 3,
  SDS_CMP_SIZE = 4
};

enum CmpDetailType
{
  SDS_HEADER_SAME = 0,
  SDS_HEADER_PLAY_NEW_BETTER = 1,
  SDS_HEADER_PLAY_OLD_BETTER = 2,
  SDS_HEADER_PLAY_DIFFERENT = 3,
  SDS_HEADER_RANK_NEW_BETTER = 4,
  SDS_HEADER_RANK_OLD_BETTER = 5,
  SDS_HEADER_RANK_DIFFERENT = 6,
  SDS_HEADER_CMP_SIZE = 7
};

enum CmpTrickType
{
  SDS_TRICK_SAME = 0,
  SDS_TRICK_PLAY_NEW_BETTER = 1,
  SDS_TRICK_PLAY_OLD_BETTER = 2,
  SDS_TRICK_PLAY_DIFFERENT = 3,
  SDS_TRICK_RANK_NEW_BETTER = 4,
  SDS_TRICK_RANK_OLD_BETTER = 5,
  SDS_TRICK_RANK_DIFFERENT = 6,
  SDS_TRICK_PLAY_NEW_ADV = 7,
  SDS_TRICK_PLAY_OLD_ADV = 8,
  SDS_TRICK_CMP_SIZE = 9
};

enum FixType
{
  SDS_FIX_UNCHANGED = 0,
  SDS_FIX_PURGED = 1,
  SDS_FIX_STRONGER = 2,
  SDS_FIX_WEAKER = 3,
  SDS_FIX_SPLIT = 4,
  SDS_FIX_COLLAPSE = 5,
  SDS_FIX_SIZE = 6
};

const CmpDetailType cmpTrickToDetail[SDS_TRICK_CMP_SIZE] =
{
  SDS_HEADER_SAME,
  SDS_HEADER_PLAY_NEW_BETTER,
  SDS_HEADER_PLAY_OLD_BETTER,
  SDS_HEADER_PLAY_DIFFERENT,
  SDS_HEADER_RANK_NEW_BETTER,
  SDS_HEADER_RANK_OLD_BETTER,
  SDS_HEADER_RANK_DIFFERENT,
  SDS_HEADER_PLAY_DIFFERENT,
  SDS_HEADER_PLAY_DIFFERENT
};

const char CMP_DETAIL_NAMES[SDS_HEADER_CMP_SIZE][10] =
{ "Same", "Play new", "Play old", "Playdiff",
  "Rank new", "Rank old", "Rankdiff" };

// A lot of the combinations can't happen in practice
const CmpDetailType 
  cmpDetailMatrix[SDS_HEADER_CMP_SIZE][SDS_HEADER_CMP_SIZE] =
{
  // SDS_HEADER_SAME
  { 
    SDS_HEADER_SAME,            // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_NEW_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_OLD_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_PLAY_NEW_BETTER
  {
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_PLAY_NEW_BETTER  // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_PLAY_OLD_BETTER
  {
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_PLAY_OLD_BETTER  // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_PLAY_DIFFERENT
  {
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_SAME
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_RANK_NEW_BETTER
  {
    SDS_HEADER_RANK_NEW_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_NEW_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_RANK_OLD_BETTER
  {
    SDS_HEADER_RANK_OLD_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_OLD_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_RANK_DIFFERENT
  {
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  }
};

const CmpTrickType 
  cmpTrickMatrix[SDS_TRICK_CMP_SIZE][SDS_TRICK_CMP_SIZE] =
{
  // SDS_TRICK_SAME
  { 
    SDS_TRICK_SAME,            // SDS_TRICK_SAME
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_RANK_NEW_BETTER, // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_RANK_OLD_BETTER, // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_NEW_ADV,    // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_OLD_ADV     // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_PLAY_NEW_BETTER
  {
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_SAME
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_NEW_BETTER  // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_PLAY_OLD_BETTER
  {
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_SAME
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_OLD_BETTER  // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_PLAY_DIFFERENT
  {
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_SAME
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_DIFFERENT   // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_RANK_NEW_BETTER
  {
    SDS_TRICK_RANK_NEW_BETTER, // SDS_TRICK_SAME
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_RANK_NEW_BETTER, // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_NEW_ADV,    // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_OLD_ADV     // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_RANK_OLD_BETTER
  {
    SDS_TRICK_RANK_OLD_BETTER, // SDS_TRICK_SAME
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_RANK_OLD_BETTER, // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_NEW_ADV,    // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_OLD_ADV     // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_RANK_DIFFERENT
  {
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_SAME
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_RANK_DIFFERENT   // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_PLAY_NEW_ADV
  {
    SDS_TRICK_PLAY_NEW_ADV,    // SDS_TRICK_SAME
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_PLAY_NEW_BETTER, // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_PLAY_NEW_ADV,    // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_NEW_ADV,    // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_DIFFERENT   // SDS_TRICK_PLAY_OLD_ADV
  },

  // SDS_TRICK_PLAY_OLD_ADV
  {
    SDS_TRICK_PLAY_OLD_ADV,    // SDS_TRICK_SAME
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_PLAY_OLD_BETTER
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_DIFFERENT
    SDS_TRICK_PLAY_OLD_ADV,    // SDS_TRICK_RANK_NEW_BETTER
    SDS_TRICK_PLAY_OLD_BETTER, // SDS_TRICK_RANK_OLD_BETTER
    SDS_TRICK_RANK_DIFFERENT,  // SDS_TRICK_RANK_DIFFERENT
    SDS_TRICK_PLAY_DIFFERENT,  // SDS_TRICK_PLAY_NEW_ADV
    SDS_TRICK_PLAY_OLD_ADV     // SDS_TRICK_PLAY_OLD_ADV
  }
};

const CmpDetailType 
  cmpDetailHardMatrix[SDS_HEADER_CMP_SIZE][SDS_HEADER_CMP_SIZE] =
{
  // SDS_HEADER_SAME
  { 
    SDS_HEADER_SAME,            // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_NEW_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_OLD_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_PLAY_NEW_BETTER
  {
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_PLAY_OLD_BETTER
  {
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_PLAY_DIFFERENT
  {
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_SAME
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_RANK_NEW_BETTER
  {
    SDS_HEADER_RANK_NEW_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_NEW_BETTER, // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_NEW_BETTER, // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_RANK_OLD_BETTER
  {
    SDS_HEADER_RANK_OLD_BETTER, // SDS_HEADER_SAME
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_OLD_BETTER, // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_OLD_BETTER, // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  },

  // SDS_HEADER_RANK_DIFFERENT
  {
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_SAME
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_NEW_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_OLD_BETTER
    SDS_HEADER_PLAY_DIFFERENT,  // SDS_HEADER_PLAY_DIFFERENT
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_NEW_BETTER
    SDS_HEADER_RANK_DIFFERENT,  // SDS_HEADER_RANK_OLD_BETTER
    SDS_HEADER_RANK_DIFFERENT   // SDS_HEADER_RANK_DIFFERENT
  }
};

enum AppendType
{
  SDS_APPEND_MERGED = 0,
  SDS_APPEND_SAME_SEG = 1,
  SDS_APPEND_NEW_SEG = 2
};

#endif

